### GET ALL USER
GET http://localhost:1337/api/v1/user
X-Auth: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjg5NzUwOTY1LCJleHAiOjE2OTAzNTU3NjV9.8FniII-q5eafRRTSHNnrTssV46CkXE6_ZCdw-0BNbJA

### GET ONE USER
GET http://localhost:1337/api/v1/user/1
X-Auth: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjg5NzUwOTY1LCJleHAiOjE2OTAzNTU3NjV9.8FniII-q5eafRRTSHNnrTssV46CkXE6_ZCdw-0BNbJA

###
PUT http://localhost:1337/api/v1/user/1
Content-Type: application/json
X-Auth: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjg5NzUwOTY1LCJleHAiOjE2OTAzNTU3NjV9.8FniII-q5eafRRTSHNnrTssV46CkXE6_ZCdw-0BNbJA

{
   "nama": "Kevin ID",
   "no_hp": "08214861241",
   "email": "test@gmail.com"
}

###
DELETE http://localhost:1337/api/v1/user/3
X-Auth: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjg5NzUwOTY1LCJleHAiOjE2OTAzNTU3NjV9.8FniII-q5eafRRTSHNnrTssV46CkXE6_ZCdw-0BNbJA